### ISSUE TITLE
[feature] add private health insurers

### ISSUE THREAD

**Issue by mokkin** [PhilLehmann/gesundheitsdatenbefreier#4]
In addition to the public insurance there are also private insurers. Shouldn't we add them too?
If yes I can try implement a list.

**Comment by PhilLehmann** [comment]
There is no reason, not to. Of course :)

**Comment by mokkin** [comment]
https://github.com/PhilLehmann/gesundheitsdatenbefreier/pull/5 should solve this.

After adding them there has to be a modification in the number validator. The specified format is only valid for public health insurers. Private ones have totally different systematics. They differ from company to company.
Therefore it should be activated only for public ones.

**Comment by PhilLehmann** [comment]
Done. Thanks a lot for your input!
